/*
 * PolyRhythm API
 *
 * The API backend for FourSee's PolyRythm 
 *
 * API version: 1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type MessageInput struct {

	Content string `json:"content"`

	Signature string `json:"signature"`

	Title string `json:"title,omitempty"`

	ExitCode int32 `json:"exit_code,omitempty"`
}
