/*
 * PolyRhythm
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package swagger-go

type PairingsList struct {
	Pairings []Pairing `json:"pairings"`
	Pagination PaginationData `json:"pagination"`
}
