/*
 * PolyRhythm
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapiGo

// The root of the Device type's schema.
type Device struct {
	Id string `json:"id,omitempty"`
	UserId string `json:"user_id"`
	Name string `json:"name"`
	PublicKey string `json:"public_key"`
	DeviceType string `json:"device_type"`
	// An optional push token. Server will never respond with this. It is only used to create/update push notification credentials.
	PushToken string `json:"push_token,omitempty"`
}
