/*
 * PolyRhythm
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapiGo

type DevicesList struct {
	Messages []Message `json:"messages"`
	Pagination PaginationData `json:"pagination"`
}
