/*
 * PolyRhythm
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// The root of the Pairing type's schema.
type Pairing struct {
	PairedDeviceId string `json:"paired_device_id,omitempty"`
}
