/*
 * PolyRhythm
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// The root of the PaginationData type's schema.
type PaginationData struct {
	Page int32 `json:"page"`
	TotalPages int32 `json:"total_pages"`
	TotalItems int32 `json:"total_items"`
	PerPage int32 `json:"per_page"`
	NextPage int32 `json:"next_page"`
}
