/*
 * PolyRhythm
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapiGo

type MessagesList struct {
	Devices []Message `json:"devices"`
	Pagination PaginationData `json:"pagination"`
}
