/*
 * PolyRhythm
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package swagger-go

// The root of the User type's schema.
type User struct {
	Id string `json:"id"`
	Email string `json:"email"`
}
