/*
 * PolyRhythm API
 *
 * The API backend for FourSee's PolyRythm 
 *
 * API version: 1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type PairingRequestInput struct {

	PublicKey string `json:"public_key,omitempty"`

	DeviceName string `json:"device_name,omitempty"`

	DeviceInfo *PairingRequestInputDeviceInfo `json:"device_info,omitempty"`
}
