/*
 * PolyRhythm API
 *
 * The API backend for FourSee's PolyRythm 
 *
 * API version: 1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type PairingRequest struct {

	Id string `json:"id,omitempty"`

	DeviceName string `json:"device_name,omitempty"`

	ShortId string `json:"short_id,omitempty"`

	Status string `json:"status,omitempty"`

	CreatedAt time.Time `json:"created_at,omitempty"`

	AcceptUrl string `json:"accept_url,omitempty"`

	IpAddress string `json:"ip_address,omitempty"`

	KeyInfo *interface{} `json:"key_info,omitempty"`
}
