/*
 * PolyRhythm API
 *
 * The API backend for FourSee's PolyRythm 
 *
 * API version: 1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type PairingRequestInputDeviceInfo struct {

	DeviceType string `json:"device_type,omitempty"`
}
