/*
 * PolyRhythm API
 *
 * The API backend for FourSee's PolyRythm 
 *
 * API version: 1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type PairingRequestCreateResponse struct {

	AcceptUrl string `json:"accept_url,omitempty"`

	ShowUrl string `json:"show_url,omitempty"`
}
