// Code generated by go-swagger; DO NOT EDIT.

package message

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// SendMessageReader is a Reader for the SendMessage structure.
type SendMessageReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SendMessageReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewSendMessageCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 422:
		result := NewSendMessageUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewSendMessageInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewSendMessageCreated creates a SendMessageCreated with default headers values
func NewSendMessageCreated() *SendMessageCreated {
	return &SendMessageCreated{}
}

/*SendMessageCreated handles this case with default header values.

Message successfully sent
*/
type SendMessageCreated struct {
}

func (o *SendMessageCreated) Error() string {
	return fmt.Sprintf("[POST /messages][%d] sendMessageCreated ", 201)
}

func (o *SendMessageCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSendMessageUnprocessableEntity creates a SendMessageUnprocessableEntity with default headers values
func NewSendMessageUnprocessableEntity() *SendMessageUnprocessableEntity {
	return &SendMessageUnprocessableEntity{}
}

/*SendMessageUnprocessableEntity handles this case with default header values.

Couldn't send message
*/
type SendMessageUnprocessableEntity struct {
}

func (o *SendMessageUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /messages][%d] sendMessageUnprocessableEntity ", 422)
}

func (o *SendMessageUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSendMessageInternalServerError creates a SendMessageInternalServerError with default headers values
func NewSendMessageInternalServerError() *SendMessageInternalServerError {
	return &SendMessageInternalServerError{}
}

/*SendMessageInternalServerError handles this case with default header values.

A server error occured
*/
type SendMessageInternalServerError struct {
}

func (o *SendMessageInternalServerError) Error() string {
	return fmt.Sprintf("[POST /messages][%d] sendMessageInternalServerError ", 500)
}

func (o *SendMessageInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
