// Code generated by go-swagger; DO NOT EDIT.

package pairing_request

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/foursee/swagger-go/models"
)

// CreatePairingRequestReader is a Reader for the CreatePairingRequest structure.
type CreatePairingRequestReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreatePairingRequestReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewCreatePairingRequestCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewCreatePairingRequestUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewCreatePairingRequestForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewCreatePairingRequestInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreatePairingRequestCreated creates a CreatePairingRequestCreated with default headers values
func NewCreatePairingRequestCreated() *CreatePairingRequestCreated {
	return &CreatePairingRequestCreated{}
}

/*CreatePairingRequestCreated handles this case with default header values.

The created pairing request
*/
type CreatePairingRequestCreated struct {
	Payload *models.PairingRequestCreateResponse
}

func (o *CreatePairingRequestCreated) Error() string {
	return fmt.Sprintf("[POST /pairing_requests][%d] createPairingRequestCreated  %+v", 201, o.Payload)
}

func (o *CreatePairingRequestCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PairingRequestCreateResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreatePairingRequestUnauthorized creates a CreatePairingRequestUnauthorized with default headers values
func NewCreatePairingRequestUnauthorized() *CreatePairingRequestUnauthorized {
	return &CreatePairingRequestUnauthorized{}
}

/*CreatePairingRequestUnauthorized handles this case with default header values.

Not authenticated - log in and try again
*/
type CreatePairingRequestUnauthorized struct {
}

func (o *CreatePairingRequestUnauthorized) Error() string {
	return fmt.Sprintf("[POST /pairing_requests][%d] createPairingRequestUnauthorized ", 401)
}

func (o *CreatePairingRequestUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreatePairingRequestForbidden creates a CreatePairingRequestForbidden with default headers values
func NewCreatePairingRequestForbidden() *CreatePairingRequestForbidden {
	return &CreatePairingRequestForbidden{}
}

/*CreatePairingRequestForbidden handles this case with default header values.

Forbidden - don't bother trying again
*/
type CreatePairingRequestForbidden struct {
}

func (o *CreatePairingRequestForbidden) Error() string {
	return fmt.Sprintf("[POST /pairing_requests][%d] createPairingRequestForbidden ", 403)
}

func (o *CreatePairingRequestForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreatePairingRequestInternalServerError creates a CreatePairingRequestInternalServerError with default headers values
func NewCreatePairingRequestInternalServerError() *CreatePairingRequestInternalServerError {
	return &CreatePairingRequestInternalServerError{}
}

/*CreatePairingRequestInternalServerError handles this case with default header values.

A server error occured
*/
type CreatePairingRequestInternalServerError struct {
}

func (o *CreatePairingRequestInternalServerError) Error() string {
	return fmt.Sprintf("[POST /pairing_requests][%d] createPairingRequestInternalServerError ", 500)
}

func (o *CreatePairingRequestInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
