// Code generated by go-swagger; DO NOT EDIT.

package pairing_request

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/foursee/swagger-go/models"
)

// NewCreatePairingRequestParams creates a new CreatePairingRequestParams object
// with the default values initialized.
func NewCreatePairingRequestParams() *CreatePairingRequestParams {
	var ()
	return &CreatePairingRequestParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreatePairingRequestParamsWithTimeout creates a new CreatePairingRequestParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreatePairingRequestParamsWithTimeout(timeout time.Duration) *CreatePairingRequestParams {
	var ()
	return &CreatePairingRequestParams{

		timeout: timeout,
	}
}

// NewCreatePairingRequestParamsWithContext creates a new CreatePairingRequestParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreatePairingRequestParamsWithContext(ctx context.Context) *CreatePairingRequestParams {
	var ()
	return &CreatePairingRequestParams{

		Context: ctx,
	}
}

// NewCreatePairingRequestParamsWithHTTPClient creates a new CreatePairingRequestParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreatePairingRequestParamsWithHTTPClient(client *http.Client) *CreatePairingRequestParams {
	var ()
	return &CreatePairingRequestParams{
		HTTPClient: client,
	}
}

/*CreatePairingRequestParams contains all the parameters to send to the API endpoint
for the create pairing request operation typically these are written to a http.Request
*/
type CreatePairingRequestParams struct {

	/*Pairingrequestinput
	  The created pairing request

	*/
	Pairingrequestinput *models.PairingRequestInput

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create pairing request params
func (o *CreatePairingRequestParams) WithTimeout(timeout time.Duration) *CreatePairingRequestParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create pairing request params
func (o *CreatePairingRequestParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create pairing request params
func (o *CreatePairingRequestParams) WithContext(ctx context.Context) *CreatePairingRequestParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create pairing request params
func (o *CreatePairingRequestParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create pairing request params
func (o *CreatePairingRequestParams) WithHTTPClient(client *http.Client) *CreatePairingRequestParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create pairing request params
func (o *CreatePairingRequestParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPairingrequestinput adds the pairingrequestinput to the create pairing request params
func (o *CreatePairingRequestParams) WithPairingrequestinput(pairingrequestinput *models.PairingRequestInput) *CreatePairingRequestParams {
	o.SetPairingrequestinput(pairingrequestinput)
	return o
}

// SetPairingrequestinput adds the pairingrequestinput to the create pairing request params
func (o *CreatePairingRequestParams) SetPairingrequestinput(pairingrequestinput *models.PairingRequestInput) {
	o.Pairingrequestinput = pairingrequestinput
}

// WriteToRequest writes these params to a swagger request
func (o *CreatePairingRequestParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Pairingrequestinput != nil {
		if err := r.SetBodyParam(o.Pairingrequestinput); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
