// Code generated by go-swagger; DO NOT EDIT.

package pairing_request

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetPairingRequestParams creates a new GetPairingRequestParams object
// with the default values initialized.
func NewGetPairingRequestParams() *GetPairingRequestParams {
	var ()
	return &GetPairingRequestParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetPairingRequestParamsWithTimeout creates a new GetPairingRequestParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetPairingRequestParamsWithTimeout(timeout time.Duration) *GetPairingRequestParams {
	var ()
	return &GetPairingRequestParams{

		timeout: timeout,
	}
}

// NewGetPairingRequestParamsWithContext creates a new GetPairingRequestParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetPairingRequestParamsWithContext(ctx context.Context) *GetPairingRequestParams {
	var ()
	return &GetPairingRequestParams{

		Context: ctx,
	}
}

// NewGetPairingRequestParamsWithHTTPClient creates a new GetPairingRequestParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetPairingRequestParamsWithHTTPClient(client *http.Client) *GetPairingRequestParams {
	var ()
	return &GetPairingRequestParams{
		HTTPClient: client,
	}
}

/*GetPairingRequestParams contains all the parameters to send to the API endpoint
for the get pairing request operation typically these are written to a http.Request
*/
type GetPairingRequestParams struct {

	/*ID
	  ID of the item

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get pairing request params
func (o *GetPairingRequestParams) WithTimeout(timeout time.Duration) *GetPairingRequestParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get pairing request params
func (o *GetPairingRequestParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get pairing request params
func (o *GetPairingRequestParams) WithContext(ctx context.Context) *GetPairingRequestParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get pairing request params
func (o *GetPairingRequestParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get pairing request params
func (o *GetPairingRequestParams) WithHTTPClient(client *http.Client) *GetPairingRequestParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get pairing request params
func (o *GetPairingRequestParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get pairing request params
func (o *GetPairingRequestParams) WithID(id string) *GetPairingRequestParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get pairing request params
func (o *GetPairingRequestParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetPairingRequestParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
