// Code generated by go-swagger; DO NOT EDIT.

package pairing_request

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/foursee/swagger-go/models"
)

// GetPairingRequestReader is a Reader for the GetPairingRequest structure.
type GetPairingRequestReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPairingRequestReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetPairingRequestOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewGetPairingRequestUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewGetPairingRequestForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewGetPairingRequestInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetPairingRequestOK creates a GetPairingRequestOK with default headers values
func NewGetPairingRequestOK() *GetPairingRequestOK {
	return &GetPairingRequestOK{}
}

/*GetPairingRequestOK handles this case with default header values.

The created pairing request
*/
type GetPairingRequestOK struct {
	Payload *models.PairingRequest
}

func (o *GetPairingRequestOK) Error() string {
	return fmt.Sprintf("[GET /pairing_requests/{id}][%d] getPairingRequestOK  %+v", 200, o.Payload)
}

func (o *GetPairingRequestOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PairingRequest)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetPairingRequestUnauthorized creates a GetPairingRequestUnauthorized with default headers values
func NewGetPairingRequestUnauthorized() *GetPairingRequestUnauthorized {
	return &GetPairingRequestUnauthorized{}
}

/*GetPairingRequestUnauthorized handles this case with default header values.

Not authenticated - log in and try again
*/
type GetPairingRequestUnauthorized struct {
}

func (o *GetPairingRequestUnauthorized) Error() string {
	return fmt.Sprintf("[GET /pairing_requests/{id}][%d] getPairingRequestUnauthorized ", 401)
}

func (o *GetPairingRequestUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetPairingRequestForbidden creates a GetPairingRequestForbidden with default headers values
func NewGetPairingRequestForbidden() *GetPairingRequestForbidden {
	return &GetPairingRequestForbidden{}
}

/*GetPairingRequestForbidden handles this case with default header values.

Forbidden - don't bother trying again
*/
type GetPairingRequestForbidden struct {
}

func (o *GetPairingRequestForbidden) Error() string {
	return fmt.Sprintf("[GET /pairing_requests/{id}][%d] getPairingRequestForbidden ", 403)
}

func (o *GetPairingRequestForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetPairingRequestInternalServerError creates a GetPairingRequestInternalServerError with default headers values
func NewGetPairingRequestInternalServerError() *GetPairingRequestInternalServerError {
	return &GetPairingRequestInternalServerError{}
}

/*GetPairingRequestInternalServerError handles this case with default header values.

A server error occured
*/
type GetPairingRequestInternalServerError struct {
}

func (o *GetPairingRequestInternalServerError) Error() string {
	return fmt.Sprintf("[GET /pairing_requests/{id}][%d] getPairingRequestInternalServerError ", 500)
}

func (o *GetPairingRequestInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
