// Code generated by go-swagger; DO NOT EDIT.

package pairing_request

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new pairing request API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for pairing request API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
CreatePairingRequest creates pairing request

Initiates a pairing request. Assumed to be done by the PolyRhythym agent
*/
func (a *Client) CreatePairingRequest(params *CreatePairingRequestParams) (*CreatePairingRequestCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCreatePairingRequestParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "createPairingRequest",
		Method:             "POST",
		PathPattern:        "/pairing_requests",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &CreatePairingRequestReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*CreatePairingRequestCreated), nil

}

/*
GetPairingRequest gets a pairing request

Gets a pairing request. Assumed to be done by the PolyRhythym agent
*/
func (a *Client) GetPairingRequest(params *GetPairingRequestParams) (*GetPairingRequestOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetPairingRequestParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getPairingRequest",
		Method:             "GET",
		PathPattern:        "/pairing_requests/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetPairingRequestReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetPairingRequestOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
