---
swagger: "2.0"
info:
  description: "The API backend for FourSee's PolyRythm "
  version: "1"
  title: "PolyRhythm API"
host: "localhost:3000"
basePath: "/v1"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /pairing_requests:
    post:
      tags:
      - "PairingRequest"
      summary: "Create pairing request"
      description: "Initiates a pairing request. Assumed to be done by the PolyRhythym\
        \ agent"
      operationId: "createPairingRequest"
      parameters:
      - in: "body"
        name: "pairingrequestinput"
        description: "The created pairing request"
        required: true
        schema:
          $ref: "#/definitions/PairingRequestInput"
        x-exportParamName: "Pairingrequestinput"
      responses:
        201:
          description: "The created pairing request"
          schema:
            $ref: "#/definitions/PairingRequestCreateResponse"
        401:
          description: "Not authenticated - log in and try again"
        403:
          description: "Forbidden - don't bother trying again"
        500:
          description: "A server error occured"
  /messages:
    post:
      tags:
      - "Message"
      summary: "Send a message"
      description: "Sends a message to a paired device. Recipient and sender are identified\
        \ via encryption & signature metadata"
      operationId: "sendMessage"
      parameters:
      - in: "body"
        name: "messageinput"
        description: "The message to send"
        required: true
        schema:
          $ref: "#/definitions/MessageInput"
        x-exportParamName: "Messageinput"
      responses:
        201:
          description: "Message successfully sent"
        422:
          description: "Couldn't send message"
        500:
          description: "A server error occured"
securityDefinitions:
  jwt:
    type: "oauth2"
    authorizationUrl: "https://base_url/"
    flow: "implicit"
    scopes:
      openid: "OpenID"
definitions:
  PairingRequest:
    properties:
      id:
        type: "string"
        format: "uuid"
        example: "12db5e50-92bc-423f-86cd-ed85335527de"
      device_name:
        type: "string"
        example: "user@hostname.org"
      short_id:
        type: "string"
        format: "uuid"
        example: "abcdef123456789ABCD"
      status:
        type: "string"
        example: "accepted"
      created_at:
        type: "string"
        format: "date-time"
        example: "2016-04-16T16:06:05Z"
      accept_url:
        type: "string"
        example: "https://baseurl/v1/pairing_requests/abcdef123456789ABCD"
      ip_address:
        type: "string"
        example: "1.0.0.1"
      key_info:
        type: "object"
        properties: {}
  PairingRequestCreateResponse:
    properties:
      accept_url:
        type: "string"
        example: "http://localhost:3000/v1/pairing_requests/6OGamCRHDPgsT9t0VK7XGL/accept"
      show_url:
        type: "string"
        example: "http://localhost:3000/v1/pairing_requests/6OGamCRHDPgsT9t0VK7XGL"
    example:
      accept_url: "http://localhost:3000/v1/pairing_requests/6OGamCRHDPgsT9t0VK7XGL/accept"
      show_url: "http://localhost:3000/v1/pairing_requests/6OGamCRHDPgsT9t0VK7XGL"
  PairingRequestInput:
    properties:
      public_key:
        type: "string"
        example: "base64encodedopenpgpkey...."
      device_name:
        type: "string"
        example: "admin@example.org"
      device_info:
        $ref: "#/definitions/PairingRequestInput_device_info"
    example:
      public_key: "base64encodedopenpgpkey...."
      device_name: "admin@example.org"
      device_info:
        device_type: "non_push"
  MessageInput:
    required:
    - "content"
    - "signature"
    properties:
      content:
        type: "string"
        example: "base64encodedopenpgpencryptedcontent...."
      signature:
        type: "string"
        example: "base64encodedopenpgpsignature...."
      title:
        type: "string"
        example: "rsync -avvc /mnt/drive1 /mnt/drive2"
      exit_code:
        type: "integer"
        example: 0
    example:
      signature: "base64encodedopenpgpsignature...."
      exit_code: 0
      title: "rsync -avvc /mnt/drive1 /mnt/drive2"
      content: "base64encodedopenpgpencryptedcontent...."
  PairingRequestInput_device_info:
    properties:
      device_type:
        type: "string"
        example: "non_push"
        default: "non_push"
    example:
      device_type: "non_push"
parameters:
  page:
    name: "page"
    in: "query"
    description: "Page to retrieve"
    required: false
    type: "integer"
    default: 1
  per_page:
    name: "per_page"
    in: "query"
    description: "Max numer of items to retrieve per page"
    required: false
    type: "integer"
    default: 10
  path_id:
    name: "id"
    in: "path"
    description: "ID of the item"
    required: true
    type: "string"
    format: "string"
