// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// PairingRequestInputDeviceInfo pairing request input device info
// swagger:model pairingRequestInputDeviceInfo
type PairingRequestInputDeviceInfo struct {

	// device type
	DeviceType *string `json:"device_type,omitempty"`
}

// Validate validates this pairing request input device info
func (m *PairingRequestInputDeviceInfo) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PairingRequestInputDeviceInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PairingRequestInputDeviceInfo) UnmarshalBinary(b []byte) error {
	var res PairingRequestInputDeviceInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
